version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build:
    # Remove if parallelism is not desired
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1"
    docker: # run the steps with Docker
      - image: circleci/openjdk:11.0.3-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Run tests in parallel # See: https://circleci.com/docs/2.0/parallelism-faster-jobs/
          # Use "./gradlew test" instead if tests are not run in parallel
          command: |
            ./gradlew test
      - store_test_results:
          # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: build/test-results/test
      - store_artifacts: # Upload test results for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: build/test-results/test
          when: always
      - run:
          name: Assemble JAR
          command: |
              ./gradlew bootJar
      # As the JAR was only assembled in the first build container, build/libs will be empty in all the other build containers.
      - store_artifacts:
          path: api/build/libs
      # - run:
      #     name: Setup Heroku
      #     command: |
      #       bash .circleci/setup-heroku.sh
      #       heroku deploy:jar "api/build/libs/api##1.0.0.null.jar" --app $HEROKU_APP_NAME
            
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}


          # run a script to set up Heroku
          
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
  deploy:
    machine:
        enabled: true
    #working_directory: /home/circleci/project/api/build/libs/
    # environment:
    #   HEROKU_APP_NAME: $HEROKU_APP_NAME # define env var $HEROKU_APP_NAME https://$HEROKU_APP_NAME.herokuapp.com
      # HEROKU_API_KEY: $HEROKU_API_KEY
    steps:
      - checkout
      - attach_workspace:
          at: .
            - restore_cache:
          keys:
            - v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Setup Heroku
          command: |
            bash .circleci/setup-heroku.sh
            heroku deploy:jar "api/build/libs/api##1.0.0.null.jar" --app $HEROKU_APP_NAME
          # run a script to set up Heroku

      # - run:
      #     command: |
      #       git add /api/build/libs/api##1.0.0.null.jar heroku dev:main
      #       git commit -m"heroku"
      #       git push heroku dev:main
      #       sleep 5 # sleep for 5 seconds to wait for dynos
      #       heroku restart

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: dev
