
version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  uTest_iTest:
    # Remove if parallelism is not desired
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1"
      SERVICE_URL: "https://$HEROKU_APP_NAME_SERVER.herokuapp.com"
      API_URL: "https://$HEROKU_APP_NAME_API.herokuapp.com"
    docker: # run the steps with Docker
      - image: circleci/openjdk:11.0.3-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Run tests in parallel # See: https://circleci.com/docs/2.0/parallelism-faster-jobs/
          # Use "./gradlew test" instead if tests are not run in parallel
          command: |
            ./gradlew test -Pprofiles=local,https,tc

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:  # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data
          path: ~/test-results
      - store_artifacts: # Upload test results for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: ~/test-results/junit         
      - run:
          name: Assembling JARs
          command: |
            ./gradlew :api:bootJar
            ./gradlew :site:bootJar
      - store_artifacts:
          path: api/build/libs
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
  # Remove if parallelism is not desired
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1"
      SERVICE_URL: "https://$HEROKU_APP_NAME_SERVER.herokuapp.com"
      API_URL: "https://$HEROKU_APP_NAME_API.herokuapp.com"
    docker: # run the steps with Docker
      - image: circleci/openjdk:11.0.3-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}     
      - run:
          name: Assembling JARs
          command: |
            ./gradlew :api:bootJar
            ./gradlew :site:bootJar
      - store_artifacts:
          path: api/build/libs
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    machine:
        enabled: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Setting up heroku
          command: |
            bash .circleci/setup-heroku.sh
      - run:
          name: Build and push api image to heroku
          command: |
            heroku container:login
            cd api
            heroku container:push web --app $HEROKU_APP_NAME_API
            heroku container:release web --app $HEROKU_APP_NAME_API
            cd ../site
            heroku container:push web --app $HEROKU_APP_NAME_SERVER
            heroku container:release web --app $HEROKU_APP_NAME_SERVER

            
  #Playwright
  playwright:
    working_directory: ~/project/
    docker:
      - image: mcr.microsoft.com/playwright:bionic
        environment:
          NODE_ENV: development # Needed if playwright is in `devDependencies`
          BASE_URL: https://$HEROKU_APP_NAME_SERVER.herokuapp.com

    steps:
      - checkout
      - restore_cache:
          paths:
            - ~/project/e2e/cache
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Playwright Installation and Testing
          command: | # BASE_URL=$HEROKU_APP_NAME_SERVER is the env variable being tested upon
            cd e2e
            npm ci
            FOLIO_JUNIT_OUTPUT_NAME=test-results/playwright_e2e_junit.xml npx folio --config=config.ts
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/e2e/
            find . -type f -regex ".*/.*xml" -exec cp {} ~/test-results/e2e/ \;
            find . -type d -regex ".*/e2e/test-results/src/test/*" -exec cp {} -r ~/test-results/e2e/ \;
          when: always
      - store_test_results:  # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data
          path: ~/test-results
      - store_artifacts: # Upload test results for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: ~/test-results/e2e
      - save_cache:
          paths:
            - ~/project/e2e/cache
          key: v2-npm-deps-{{ checksum "package-lock.json" }}

workflows:
  version: 2
#   test_all:
#     jobs:
#     - minimal_core

  build-and-deploy:
    jobs:
      # - uTest_iTest
      # - build:
      #     requires:
      #       - uTest_iTest
      # - deploy:
      #     requires:
      #       - uTest_iTest
      #       - build
      #     filters:
      #       branches:
      #         only: dev
      # - playwright: # Make sure to add colon back in when adding conditions
      #     requires:
      #       - uTest_iTest
      #       - build
      #       # - deploy
      #     filters:
      #       branches:
      #         only: billy
      playwright
